import jsPDF from "jspdf";
import { motion } from "framer-motion";

function DownloadReport({ data }) {

  const generatePDF = () => {

    const doc = new jsPDF();

    const score = data?.score || 0;

    let verdict = "";

    if (score >= 80) {
      verdict = "Highly Recommended";
    }
    else if (score >= 60) {
      verdict = "Recommended";
    }
    else if (score >= 40) {
      verdict = "Average Candidate";
    }
    else {
      verdict = "Needs Improvement";
    }

    const interviewChance = Math.min(
      95,
      Math.max(20, score)
    );

    // =================================================
    // HEADER
    // =================================================

    doc.setFontSize(22);
    doc.text(
      "AI Resume Analysis Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Generated by ResumeAI`,
      20,
      30
    );

    // =================================================
    // SCORE
    // =================================================

    doc.setFontSize(16);

    doc.text(
      `ATS Score: ${score}%`,
      20,
      50
    );

    doc.text(
      `Status: ${data?.status || "N/A"}`,
      20,
      60
    );

    doc.text(
      `Recruiter Verdict: ${verdict}`,
      20,
      70
    );

    doc.text(
      `Interview Probability: ${interviewChance}%`,
      20,
      80
    );

    let y = 100;

    // =================================================
    // MATCHED SKILLS
    // =================================================

    doc.setFontSize(16);

    doc.text(
      "Matched Skills",
      20,
      y
    );

    y += 10;

    (data?.matched_skills || []).forEach(
      (skill) => {

        doc.setFontSize(12);

        doc.text(
          `• ${skill}`,
          25,
          y
        );

        y += 8;

      }
    );

    // =================================================
    // MISSING SKILLS
    // =================================================

    y += 10;

    doc.setFontSize(16);

    doc.text(
      "Missing Skills",
      20,
      y
    );

    y += 10;

    (data?.missing_skills || []).forEach(
      (skill) => {

        doc.setFontSize(12);

        doc.text(
          `• ${skill}`,
          25,
          y
        );

        y += 8;

      }
    );

    // =================================================
    // AI RECOMMENDATIONS
    // =================================================

    y += 10;

    doc.setFontSize(16);

    doc.text(
      "AI Recommendations",
      20,
      y
    );

    y += 10;

    (data?.suggestions || []).forEach(
      (item) => {

        doc.setFontSize(12);

        doc.text(
          `• ${item}`,
          25,
          y
        );

        y += 8;

      }
    );

    // =================================================
    // FOOTER
    // =================================================

    y += 15;

    doc.setFontSize(10);

    doc.text(
      "This report was generated automatically using ResumeAI ATS Analysis Engine.",
      20,
      y
    );

    doc.save("ResumeAI_Report.pdf");

  };

  return (

    <motion.div

      whileHover={{
        scale: 1.02
      }}

      className="
      bg-white/5
      backdrop-blur-xl
      border
      border-white/10
      rounded-3xl
      p-8
      shadow-2xl
      hover:border-green-500/30
      transition-all
      duration-300"
    >

      <h2
        className="
        text-3xl
        font-bold
        mb-6"
      >
        Report Center
      </h2>

      <div
        className="
        bg-green-500/10
        border
        border-green-500/20
        rounded-2xl
        p-5"
      >

        <h3
          className="
          text-xl
          font-semibold
          text-green-400"
        >
          Professional PDF Report
        </h3>

        <p
          className="
          text-gray-300
          mt-3"
        >
          Download a complete AI-generated
          resume analysis report.
        </p>

        <ul
          className="
          mt-4
          space-y-2
          text-gray-400"
        >
          <li>✅ ATS Score</li>
          <li>✅ Match Status</li>
          <li>✅ Matched Skills</li>
          <li>✅ Missing Skills</li>
          <li>✅ AI Recommendations</li>
          <li>✅ Recruiter Verdict</li>
          <li>✅ Interview Probability</li>
        </ul>

      </div>

      <motion.button

        whileTap={{
          scale: 0.95
        }}

        onClick={generatePDF}

        className="
        w-full
        mt-8
        py-4
        rounded-2xl
        bg-gradient-to-r
        from-green-500
        via-emerald-500
        to-teal-500
        hover:scale-[1.02]
        transition-all
        text-xl
        font-bold
        shadow-xl"
      >
        📄 Download PDF Report
      </motion.button>

    </motion.div>

  );

}

export default DownloadReport;